### ISSUE TITLE
API to get organisational domains using public suffix list

### ISSUE THREAD

**Issue by Dreamsorcerer** [w3c/webextensions#58] opened 2021-08-16 22:04 UTC
In order to get the organisational domain in an extension (rather than the sub-domain), it is currently required to download the list from publicsuffix.org and then write your own code to parse it and search it.

I believe browsers must already have this list installed and have a way of using it, so it would be great to open access to that to extensions.

Issues with the current approach include:

- Needing to add a ~100KB data file to the extension. (See this file I've used as an example: https://github.com/AiondaDotCom/trashmail-addon/blob/master/public_suffix.json)
- Needing to pre-process the file to allow the search to be efficient. (For example: https://github.com/AiondaDotCom/trashmail-addon/blob/master/update_suffixes.py)
- Needing to write an efficient algorithm for searching the dataset in order to avoid slowing down page loads (which many developers probably wouldn't know how to do). (For example: https://github.com/AiondaDotCom/trashmail-addon/blob/master/publicsuffixlist.js)
- Needing to update the extension regularly just to keep the suffix list up-to-date.
- As there are "naughty" words in the suffix list, this tends to trip automated checks and forces the extension to have a manual review.

**Comment by nir-walkme** [comment] 2021-08-19 08:08
Great idea and actually we need this also in the webpage context and not just in extension.

**Comment by ariasuni** [comment] 2021-08-20 09:33
I agree with all your points, but in my opinion, this is something that should be available as a standard Web API and not specifically for WebExtensions.

**Comment by Rob--W** [comment] 2021-08-20 15:37
What actual use cases do you have mind?

The Public Suffix List has some utility, but also downsides as acknowledged in the following locations:

* https://url.spec.whatwg.org/#warning-avoid-psl
* https://github.com/sleevi/psl-problems

Exposing the raw content of the list through an API may do more harm than good (e.g. when used by developers who do not understand the nuances of the Public Suffix List).

**Comment by ariasuni** [comment] 2021-08-20 16:06
I think what @Dreamsorcerer was suggesting is something like [tldts](https://github.com/remusao/tldts).

**Comment by Dreamsorcerer** [comment] 2021-08-20 20:29
> What actual use cases do you have mind?

The main thing the API would need to do is return the organisational domain for a given URL. There are many use cases for this, for example, the linked web extension uses this to show previously generated addresses across an organisation's website.

Firefox also does this exact same thing for password management, where the password autocomplete will show credentials created at mail.google.com when trying to login at calendar.google.com. So, Firefox definitely already has this functionality internally, and that's what I want to avoid duplicating.

**Comment by patrickkettner** [comment] 2024-03-20 21:20
Closing as a duplicate of #231, only because we had had more discussion there.

**Closed as duplicate by patrickkettner** 2024-03-20 21:20 UTC
Labels: enhancement
